---
- name: Parsing multiple vars
  gather_facts: yes
  hosts: all

  tasks:

    - name: display hostvars
      debug: 
        var: hostvars[inventory_hostname].my_var_cadre

    - name: display hostvars
      debug:
        var: hostvars[inventory_hostname].my_var_project

    - name: display hostvars
      debug:
        var: hostvars[inventory_hostname]

