---
- name: Parsing multiple vars
  gather_facts: yes
  hosts: all

  tasks:

    - import_role: 
        name: cadre

    - name: display cadre (default)
      debug: 
        var: my_var_cadre_low

    - name: display cadre (vars)
      debug:
        var: my_var_cadre_high

    - name: display cadre (web)
      debug:
        var: cadre_resource.web
      when:  "'web' in group_names"

    - name: display cadre (mw)
      debug:
        var: cadre_resource.mw
      when:  "'mw' in group_names"

    - name: display project mw
      debug:
        var: hostvars[inventory_hostname].my_var_project_mw
      when:  hostvars[inventory_hostname].my_var_project_mw is defined

    - name: display project web
      debug:
        var: hostvars[inventory_hostname].my_var_project_web
      when: hostvars[inventory_hostname].my_var_project_web is defined

    - name: display host_vars
      debug: 
        var: hostvars[inventory_hostname].special_host_var
      when: hostvars[inventory_hostname].special_host_var

    - name: display arbitrary secret
      debug: 
        var:  sqlpass 
      run_once: true
