---
- name: Parsing multiple vars
  gather_facts: yes
  hosts: all

  tasks:

    - include_role: 
        name: cadre

    - name: display cadre (default)
      debug: 
        var: my_var_cadre_low

    - name: display cadre (vars)
      debug:
        var: my_var_cadre_high

    - name: display mw
      debug:
        var: hostvars[inventory_hostname].my_var_project_mw

    - name: display web
      debug:
        var: hostvars[inventory_hostname].my_var_project_web

    - debug:
        var: vars

