---
- name: Read multiple values on targets
  gather_facts: yes
  hosts: all

  tasks:

    # - name: Find the config files
    #   find: 
    #     path: /mw_config
    #     pattern: '*.cfg'
    #   register: config_files

    - name: Reading file contents
      slurp:
        src: "{{ item }}"
      register: config_values
      with_fileglob: "/mw_config/*.cfg"

    - name: Display config values
      debug:
        var: config_values
