---
- name: Read multiple values on targets
  gather_facts: yes
  hosts: all

  tasks:

    - name: Get files on remote machine
      find:
        paths: /mw_config 
        pattern: '*.cfg'
      register: config_files

    - name: Reading file contents
      slurp:
        src: "{{ item.path }}"
      register: config_values
      loop: "{{ config_files.files }}"

    - name: Display config values
      debug:
        msg: "{{ config_values }}"

    - name: Display config values
      debug:
        msg: "{{ item['content'] | b64decode }}"
      loop: "{{ config_values.results }}"

    - name: Store config values
      set_fact:
        config_report: "{{ item['content'] | b64decode }}"
      loop: "{{ config_values.results }}"

    - name: Display config report
      debug:
        var: config_report
      