---
- name: Read multiple values on targets
  gather_facts: yes
  hosts: all

  tasks:

    - name: Get files on remote machine
      find:
        paths: /mw_config 
        pattern: '*.cfg'
      register: config_files

    - name: Reading file contents
      slurp:
        src: "{{ item.path }}"
        remote_src: true
      register: config_values
      with: config_files.path

    - name: Display config values
      debug:
        var: config_values
